BaseConfig:
  minDetectorConfidence: 0.25

TargetManagement:
  enableBboxUnClipping: 1
  maxTargetsPerStream: 150
  minIouDiff4NewTarget: 0.5
  probationAge: 3
  maxShadowTrackingAge: 30
  earlyTerminationAge: 1

TrajectoryManagement:
  useUniqueID: 1

DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 0
  minMatchingScore4Overall: 0.0
  minMatchingScore4SizeSimilarity: 0.6
  minMatchingScore4Iou: 0.0

StateEstimator:
  stateEstimatorType: 2
  processNoiseVar4Loc: 2.0
  processNoiseVar4Size: 1.0
  processNoiseVar4Vel: 0.1
  measurementNoiseVar4Detector: 4.0

VisualTracker:
  visualTrackerType: 1
  useColorNames: 1
  useHog: 1
