sources:
  office_pantry:
    label: Office Pantry
    type: rtsp
    uri_env: CAMERA_OFFICE_PANTRY_RTSP
    latency: 300
    protocol: tcp
    reconnect: true
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0

  office_activity_area:
    label: Office Activity Area
    type: rtsp
    uri_env: CAMERA_OFFICE_ACTIVITY_AREA_RTSP
    latency: 500
    protocol: tcp
    reconnect: true
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0

  usb_camera_0:
    label: USB Camera 0
    type: usb
    device: /dev/video0
    width: 640
    height: 480
    fps: 30
    usb_format: mjpeg
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0

  video_file_0:
    label: Object Detection
    type: file
    path: /home/ansari/Documents/dataset/detection/train.mp4
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0
  
  video_file_1:
    label: People Demo 1
    type: file
    path: /home/ansari/Videos/Demo1.mkv
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0

  video_file_2:
    label: People Demo 2
    type: file
    path: /home/ansari/Videos/Demo2.mkv
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0

  video_file_3:
    label: People Demo 3
    type: file
    path: /home/ansari/Videos/Demo3.mkv
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0
  
  video_road_segmentation:
    label: Road Segmentation
    type: file
    path: /home/ansari/Videos/road_segmentation.mp4
    display_sink: ximagesink
    inference:
      fps: 30
      width: 640
      height: 0
