sources:
  office_pantry:
    label: Office Pantry
    type: rtsp
    uri_env: CAMERA_OFFICE_PANTRY_RTSP
    latency: 300
    protocol: tcp
    reconnect: true
    inference:
      fps: 5
      width: 640
      height: 0

  office_activity_area:
    label: Office Activity Area
    type: rtsp
    uri_env: CAMERA_OFFICE_ACTIVITY_AREA_RTSP
    latency: 500
    protocol: tcp
    reconnect: true
    inference:
      fps: 5
      width: 640
      height: 0

  usb_camera_0:
    label: USB Camera 0
    type: usb
    device: 0
    width: 1280
    height: 720
    fps: 30
    usb_format: raw
    inference:
      fps: 5
      width: 640
      height: 0

  usb_camera_1:
    label: USB Camera 1
    type: usb
    device: 1
    width: 1920
    height: 1080
    fps: 30
    usb_format: raw
    inference:
      fps: 5
      width: 640
      height: 0
